/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.van.model;

import java.io.Serializable;

import android.graphics.Bitmap;
import android.graphics.drawable.Drawable;
import android.os.DropBoxManager;

public class Articles implements Serializable, Comparable<Object> {
	boolean isAscending;
	private boolean isGroupElementExpanded;
	private String articlesCost;
	private String articlesDescription;
	private Bitmap articlesImageUrl;
	private String articlesMediaUrl;
	private String articlesId;
	private String articlesLength;
	private String articlesDateIssue;
	private String articlesLevel;
	private String articlesMediaType;
	private int articlesProgress;
	private String articlesTitle;
	
	public String getArticlesDateIssue() {
		return articlesDateIssue;
	}

	public void setArticlesDateIssue(String articlesDateIssue) {
		this.articlesDateIssue = articlesDateIssue;
	}

	public Bitmap getArticlesImageUrl() {
		return articlesImageUrl;
	}

	public String getArticlesMediaUrl() {
		return articlesMediaUrl;
	}

	public void setArticlesMediaUrl(String articlesMediaUrl) {
		this.articlesMediaUrl = articlesMediaUrl;
	}

	public void setArticlesImageUrl(Bitmap articlesImageUrl) {
		this.articlesImageUrl = articlesImageUrl;
	}

	public String getArticlesId() {
		return articlesId;
	}

	public void setAticlesId(String articlesId) {
		this.articlesId = articlesId;
	}

	public String getArticlesTitle() {
		return articlesTitle;
	}

	public void setArticlesTitle(String articlesTitle) {
		this.articlesTitle = articlesTitle;
	}

	public String getArticlesCost() {
		return articlesCost;
	}

	public void setArticlesCost(String articlesCost) {
		this.articlesCost = articlesCost;
	}

	public String getArticlesLevel() {
		return articlesLevel;
	}

	public void setArticlesLevel(String articlesLevel) {
		this.articlesLevel = articlesLevel;
	}

	public String getArticlesMediaType() {
		return articlesMediaType;
	}

	public void setArticlesMediaType(String articlesMediaType) {
		this.articlesMediaType = articlesMediaType;
	}

	public String getArticlesDescription() {
		return articlesDescription;
	}

	public void setArticlesDescription(String articlesDescription) {
		this.articlesDescription = articlesDescription;
	}

	public String getArticlesLength() {
		return articlesLength;
	}

	public void setArticlesLength(String articlesLength) {
		this.articlesLength = articlesLength;
	}

	public int getArticlesProgress() {
		return articlesProgress;
	}

	public void setArticlesProgress(int articlesProgress) {
		this.articlesProgress = articlesProgress;
	}

	public boolean isGroupElementExpanded() {
		return isGroupElementExpanded;
	}

	public void setGroupElementExpanded(boolean isGroupElementExpanded) {
		this.isGroupElementExpanded = isGroupElementExpanded;
	}

//	public String getArticlesNumberOfStep() {
//		return articlesNumberOfStep;
//	}
//
//	public void setArticlesNumberOfStep(String articlesNumberOfStep) {
//		articlesNumberOfStep = articlesNumberOfStep;
//	}

	public int compareTo(Articles articles) {
		String compareQuantity = "0";
		String thisArticlesCost;
		if (articles.getArticlesCost().equalsIgnoreCase("FREE")) {
			compareQuantity = "";
		} else {
			compareQuantity = articles.getArticlesCost();
		}
		if (getArticlesCost().equalsIgnoreCase("FREE")) {
			thisArticlesCost = "";
		} else {
			thisArticlesCost = getArticlesCost();
		}
		int returnValue = thisArticlesCost.compareToIgnoreCase(compareQuantity);
		return returnValue;
	}

	@Override
	public int compareTo(Object another) {
		// TODO Auto-generated method stub
		return 0;
	}
}
